begin;
select plan(15);
select has_table('public', 'scan_runs', 'scan runs exist');
select has_table('public', 'editorial_candidates', 'private candidates exist');
select has_table('public', 'approved_change_sets', 'reviewed change sets exist');
select has_table('public', 'compliance_registry', 'compliance registry exists');
select has_table('public', 'compliance_requests', 'takedown and grievance requests exist');
select has_table('public', 'vendor_compliance', 'vendor register exists');
select has_table('public', 'retention_schedules', 'retention schedules exist');
select is((select scheduler_enabled from public.discovery_schedule_settings where singleton), false, 'production scheduler defaults off');
select is((select dry_run_only from public.discovery_schedule_settings where singleton), true, 'scanner defaults to dry run');
select is((select count(*)::integer from public.compliance_registry where production_enabled), 0, 'no connector is production enabled');
select is((select count(*)::integer from public.scan_sources where enabled), 0, 'no source is enabled');
select throws_ok($$update public.compliance_registry set production_enabled = true where subject_key = 'rss-atom'$$, '23514', null, 'unreviewed connector cannot be enabled');
select throws_ok($$update public.scan_sources set enabled = true where name = 'Government of Assam'$$, '23514', 'A compliance review is required before enabling a source', 'source without compliance cannot run');
set local role anon;
select throws_ok('select count(*) from public.discovered_items', '42501', 'permission denied for table discovered_items', 'public cannot read retained evidence');
select throws_ok('select count(*) from public.compliance_registry', '42501', 'permission denied for table compliance_registry', 'public cannot read legal notes');
reset role;
select * from finish();
rollback;
